/*
 * Generated by the UCC compiler
 * Source file: {% for file in files %}
 *   - {{ file }}{% endfor %}
 *
 * File stem: {{ output_stem }}
 *
 * Copyright (c) 2025 whs31
 * https://github.com/whs31/ucc
 *
 * DO NOT MODIFY. THIS FILE IS AUTO-GENERATED BY THE BUILD SYSTEM
 */
#pragma once

#include <string>
#include <string_view>
{% if with_nlohmann %}#include <nlohmann/json.hpp>{% endif %}

namespace {{ namespace }} {
  {% for (stem, json) in json_data %}
  inline namespace {{ stem }} {
    [[maybe_unused]]
    inline auto constexpr {{ stem }}_c_str = R"({{ json | tojson | safe }})";{% if with_nlohmann %}

    [[maybe_unused]]
    static inline auto {{ stem }}_json = nlohmann::json::parse({{ stem }}_c_str);{% endif %}
  } // namespace {{ stem }}
  {% endfor %}
} // namespace {{ namespace }}