/*
 * Generated by the whs31's ucc compiler (wucc)
 * Source file(s): {% for file in files %}
 *   - {{ file }}{% endfor %}
 *
 * Header: {{ filename }}.rc.h
 * Source: {{ filename }}.rc.cc
 *
 * Copyright (c) 2025 whs31
 * https://github.com/whs31/wucc
 * https://crate.io/crates/wucc
 *
 * DO NOT MODIFY. THIS FILE IS AUTO-GENERATED BY THE BUILD SYSTEM
 */
#pragma once

#include <span>
#include <utility>
#include <string>
#include <string_view>

namespace {{ namespace }} {
  {% for stem in text_getters %}
    [[nodiscard]]
    [[maybe_unused]]
    std::string_view {{ stem }}() noexcept;
  {% endfor %}
  {% for stem in binary_getters %}
    [[nodiscard]]
    [[maybe_unused]]
    std::span<std::byte const> {{ stem }}() noexcept;
  {% endfor %}
} // namespace {{ namespace }}